apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devops
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    circleci.com/project-slug: github/dhanu0001/demo-app
#     github.com/project-slug: dhanu0001/demo-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:ShikhaVashishtha
  lifecycle: experimental
